### ISSUE TITLE
Increase Parameter Limit on type of UrlEncoded

### ISSUE THREAD

**Issue by umaams** [adonisjs/adonis-bodyparser#12]
How to increase parameterLimit on type of UrlEncoded?
I try to add parameterLimit: 100000 in config/bodyParser.js file and still not working

**Comment by thetutlage** [comment]
Please make sure to read the new issue guidelines. The Github issues reporter is only for reporting bugs. This will help us in keeping the bug reporter clean and easy to work with 🙏.

Please ask the question on the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)
