### ISSUE TITLE
file.runValidations() has unexpected behavior when manually processing file

### ISSUE THREAD

**Issue by borie88** [adonisjs/adonis-bodyparser#15]
I am trying to manually process a file using the request.multipart.file() callback. Since I want to use the provided validation functions within the callback, I await file.runValidations() (found this from the source code). The validation for file type works, but it doesn't work for verifying file size (looks like its due to the async nature of how the File class gets the size). Is there another way to do this, or should the File class get size from file.stream.byteCount instead?

*edit: Actually the file.error() always returns an empty object unless a type error is specifically found.

Code:
```
const options = {
  size: '10kb',
  types: ['image', 'video']
}
request.multipart.file('file', options, async (file) => {
        await file.runValidations()
        const fileError = file.error()
        // if size validation is set, fileError will always return {}
        if (fileError) throw fileError
        // or else process file normally
})
await request.multipart.process()
```

**Comment by RomainLanz** [comment]
Hey @borie88! 👋 

Sorry for the late reply.
Could you please create a repository with the minimum amount of code to reproduce the issue?

**Comment by thetutlage** [comment]
Actually this is not possible, since you are trying to validate the size of the stream which is unknown unless you consume the stream.

**Comment by wozzp** [comment]
@borie88 

`file.size = file.stream.byteCount`
`await file.runValidations()`

its work to me :)
