### ISSUE TITLE
Multiparty options are hardcoded

### ISSUE THREAD

**Issue by donnysim** [adonisjs/adonis-bodyparser#18]
## Package version
2.0.9

## Node.js and npm version
Node v10.9.0 NPM v6.6.0

## Sample Code (to reproduce the issue)
Multiparty options are hardcoded and not customizable in AdonisJs in `node_modules\@adonisjs\bodyparser\src\Multipart\index.js`
```
    this._multipartyOptions = {
      autoFields: true,
      autoFiles: false
    }
```

This prevents changing options like `maxFields` and now I'm stuck without being able to do anything because I need more than the default of 1000 fields with simple forms.

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
