### ISSUE TITLE
Unixtime in tmp file name

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-bodyparser#2]
_From @1001v on October 26, 2017 17:54_

Hello. I've reproduced sample code from [File uploads guide](http://dev.adonisjs.com/docs/4.0/file-uploads), and it seems that **request.file** method uses unixtime integer to name the tmp file. So the case when two different file upload instances get the same tmp file name isn't rare, i tested. Sometimes two-three upload requests would be enough to fire the issue. I bet the tmp file name should be more unique. Thank you.

_Copied from original issue: adonisjs/adonis-framework#685_

**Comment by thetutlage** [comment]
_From @RomainLanz on October 27, 2017 13:35_

Hey @1001v! 👋 

May you provide a repository so I can replicate this issue?

**Comment by thetutlage** [comment]
Yeah, this can cause issue, maybe we can use a better way to define the unique names. I will make the change.

**Comment by thetutlage** [comment]
_From @RomainLanz on October 28, 2017 7:40_

Why not use the [`uuid`](https://www.npmjs.com/package/uuid) package?

**Comment by thetutlage** [comment]
_From @1001v on October 28, 2017 7:41_

I think you could use Math.random() + Date.now()

**Comment by thetutlage** [comment]
_From @RomainLanz on October 28, 2017 8:57_

`Math.random()` + `Date.now()` will be for sure faster but it can still create colision.
 
Also, a simple `uuid` generator got `263,728 ops/s` which isn't to slow to be used imo.


**Code for reference:**
```js
function b(a){return a?(a^Math.random()*16>>a/4).toString(16):([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,b)}
```

**Comment by thetutlage** [comment]
@RomainLanz Thanks will make the required changes

**Comment by 1001v** [comment]
@thetutlage , thank you.

**Comment by thetutlage** [comment]
Also added option to define custom `tmp file name` via config
