### ISSUE TITLE
Parser for unsupported media type

### ISSUE THREAD

**Issue by amitguptagwl** [adonisjs/adonis-bodyparser#6]
What happens when an unsupported content type is given? 
What if I give an XML payload with content type "application/rss+xml"?
Can I register custom bodyparser when some mime types are not handled by default? or should I raise PR to modify main code to handle other mime types? (I don't think it is a good idea)

**Comment by RomainLanz** [comment]
Hey @amitguptagwl! 👋 

You can add it to the `[raw](https://github.com/adonisjs/adonis-bodyparser/blob/master/config/bodyParser.js#L62)` config so it'll not be parsed by any of the default parsers.

Then you can do whatever you want with it.

**Comment by amitguptagwl** [comment]
Thanks for the response. Once I added the type to the `raw.types`, how will I ask adonis to use my custom body parser to this particular type. Or in case if I have 2 different parsers for 2 different types.

**Comment by RomainLanz** [comment]
You can create your own middleware and run it after the middleware of the body parser.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
